[project]
name = "bentoai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alain-16", email = "mugishalain81@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosmtplib>=5.1.2",
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "openai>=3.3.1",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy[asyncio]>=2.0.52",
]

[project.scripts]
bentoai = "bentoai:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
