"""add pending_questions to missions

Revision ID: ffa8ec06dcad
Revises: 6d66335f72b4
Create Date: 2026-09-02 11:17:06.924930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffa8ec06dcad'
down_revision: Union[str, Sequence[str], None] = '6d66335f72b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_missions', sa.Column('pending_questions', postgresql.JSONB(astext_type=sa.Text()),server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.alter_column('shopping_missions', 'basket_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shopping_missions', 'basket_options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.drop_column('shopping_missions', 'pending_questions')
    # ### end Alembic commands ###
