"""initial schema

Revision ID: d99bd67f7d87
Revises: 
Create Date: 2026-08-26 18:29:17.077663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd99bd67f7d87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.Enum('shopify_global', 'ucp', 'other', name='providertype', native_enum=False, length=32), nullable=False),
    sa.Column('ucp_profile_url', sa.String(length=500), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('auth_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'unreachable', name='merchantstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_index(op.f('ix_merchants_domain'), 'merchants', ['domain'], unique=True)
    op.create_table('otp_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    op.create_index(op.f('ix_otp_codes_email'), 'otp_codes', ['email'], unique=True)
    op.create_index('ix_otp_codes_email_expires_at', 'otp_codes', ['email', 'expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.Uuid(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_id_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('shopping_missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'planning', 'searching', 'evaluating', 'review', 'basket_ready', 'checkout_pending', 'purchased', 'tracking', 'complete', name='missionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('planning_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_shopping_missions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_missions'))
    )
    op.create_index(op.f('ix_shopping_missions_user_id'), 'shopping_missions', ['user_id'], unique=False)
    op.create_index('ix_shopping_missions_user_id_status', 'shopping_missions', ['user_id', 'status'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('user', 'system', 'agent', 'provider', name='actortype', native_enum=False, length=32), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['shopping_missions.id'], name=op.f('fk_audit_events_mission_id_shopping_missions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_mission_id'), 'audit_events', ['mission_id'], unique=False)
    op.create_index('ix_audit_events_mission_id_created_at', 'audit_events', ['mission_id', 'created_at'], unique=False)
    op.create_table('baskets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'checked_out', 'abandoned', name='basketstatus', native_enum=False, length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['shopping_missions.id'], name=op.f('fk_baskets_mission_id_shopping_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baskets'))
    )
    op.create_index(op.f('ix_baskets_mission_id'), 'baskets', ['mission_id'], unique=False)
    op.create_table('mission_requirements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('required', 'optional', name='requirementpriority', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'satisfied', 'skipped', name='requirementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('budget_allocation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['shopping_missions.id'], name=op.f('fk_mission_requirements_mission_id_shopping_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mission_requirements'))
    )
    op.create_index(op.f('ix_mission_requirements_mission_id'), 'mission_requirements', ['mission_id'], unique=False)
    op.create_table('basket_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('basket_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('source_product_id', sa.String(length=255), nullable=False),
    sa.Column('source_variant_id', sa.String(length=255), nullable=True),
    sa.Column('title_snapshot', sa.String(length=500), nullable=False),
    sa.Column('variant_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('item_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_basket_items_basket_id_baskets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_basket_items_merchant_id_merchants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['mission_requirements.id'], name=op.f('fk_basket_items_requirement_id_mission_requirements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_basket_items'))
    )
    op.create_index(op.f('ix_basket_items_basket_id'), 'basket_items', ['basket_id'], unique=False)
    op.create_index(op.f('ix_basket_items_merchant_id'), 'basket_items', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_basket_items_requirement_id'), 'basket_items', ['requirement_id'], unique=False)
    op.create_table('checkouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('basket_id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'completed', 'failed', 'expired', name='checkoutstatus', native_enum=False, length=32), nullable=False),
    sa.Column('external_checkout_id', sa.String(length=255), nullable=True),
    sa.Column('checkout_url', sa.String(length=1000), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], name=op.f('fk_checkouts_basket_id_baskets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_checkouts_merchant_id_merchants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['shopping_missions.id'], name=op.f('fk_checkouts_mission_id_shopping_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkouts')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_checkouts_idempotency_key'))
    )
    op.create_index(op.f('ix_checkouts_basket_id'), 'checkouts', ['basket_id'], unique=False)
    op.create_index(op.f('ix_checkouts_merchant_id'), 'checkouts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_checkouts_mission_id'), 'checkouts', ['mission_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('checkout_id', sa.Uuid(), nullable=True),
    sa.Column('merchant_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_order_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'refunded', name='orderstatus', native_enum=False, length=32), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.String(length=1000), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkouts.id'], name=op.f('fk_orders_checkout_id_checkouts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_orders_merchant_id_merchants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['shopping_missions.id'], name=op.f('fk_orders_mission_id_shopping_missions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('provider', 'external_order_id', name='uq_orders_provider_external_order_id')
    )
    op.create_index(op.f('ix_orders_checkout_id'), 'orders', ['checkout_id'], unique=False)
    op.create_index(op.f('ix_orders_merchant_id'), 'orders', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_orders_mission_id'), 'orders', ['mission_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('basket_item_id', sa.Uuid(), nullable=True),
    sa.Column('source_product_id', sa.String(length=255), nullable=False),
    sa.Column('title_snapshot', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['basket_item_id'], ['basket_items.id'], name=op.f('fk_order_items_basket_item_id_basket_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_mission_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_merchant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_checkout_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_checkouts_mission_id'), table_name='checkouts')
    op.drop_index(op.f('ix_checkouts_merchant_id'), table_name='checkouts')
    op.drop_index(op.f('ix_checkouts_basket_id'), table_name='checkouts')
    op.drop_table('checkouts')
    op.drop_index(op.f('ix_basket_items_requirement_id'), table_name='basket_items')
    op.drop_index(op.f('ix_basket_items_merchant_id'), table_name='basket_items')
    op.drop_index(op.f('ix_basket_items_basket_id'), table_name='basket_items')
    op.drop_table('basket_items')
    op.drop_index(op.f('ix_mission_requirements_mission_id'), table_name='mission_requirements')
    op.drop_table('mission_requirements')
    op.drop_index(op.f('ix_baskets_mission_id'), table_name='baskets')
    op.drop_table('baskets')
    op.drop_index('ix_audit_events_mission_id_created_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_mission_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_shopping_missions_user_id_status', table_name='shopping_missions')
    op.drop_index(op.f('ix_shopping_missions_user_id'), table_name='shopping_missions')
    op.drop_table('shopping_missions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_otp_codes_email_expires_at', table_name='otp_codes')
    op.drop_index(op.f('ix_otp_codes_email'), table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_merchants_domain'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
